


var conditionParts = [
    "condition",
    "item_type",
    "item_subtype",
    "material",
    "flags",
    "value"
]
var condOperators = [
    {
        name: "Not",
        symbol: "!=",
    },
    {
        name: "AtLeast",
        symbol: ">=",
    },
    {
        name: "AtMost",
        symbol: "<=",
    },
    {
        name: "GreaterThan",
        symbol: ">",
    },
    {
        name: "LessThan",
        symbol: "<",
    },
    {
        name: "Exactly",
        symbol: "==",
    }
]

var data = [];
data["types"] = [
    "NONE",
    "BAR",
    "SMALLGEM",
    "BLOCKS",
    "ROUGH",
    "BOULDER",
    "WOOD",
    "DOOR",
    "FLOODGATE",
    "BED",
    "CHAIR",
    "CHAIN",
    "FLASK",
    "GOBLET",
    "INSTRUMENT",
    "TOY",
    "WINDOW",
    "CAGE",
    "BARREL",
    "BUCKET",
    "ANIMALTRAP",
    "TABLE",
    "COFFIN",
    "STATUE",
    "CORPSE",
    "WEAPON",
    "ARMOR",
    "SHOES",
    "SHIELD",
    "HELM",
    "GLOVES",
    "BOX",
    "BAG",
    "BIN",
    "ARMORSTAND",
    "WEAPONRACK",
    "CABINET",
    "FIGURINE",
    "AMULET",
    "SCEPTER",
    "AMMO",
    "CROWN",
    "RING",
    "EARRING",
    "BRACELET",
    "GEM",
    "ANVIL",
    "CORPSEPIECE",
    "REMAINS",
    "MEAT",
    "FISH",
    "FISH_RAW",
    "VERMIN",
    "PET",
    "SEEDS",
    "PLANT",
    "SKIN_TANNED",
    "PLANT_GROWTH",
    "THREAD",
    "CLOTH",
    "TOTEM",
    "PANTS",
    "BACKPACK",
    "QUIVER",
    "CATAPULTPARTS",
    "BALLISTAPARTS",
    "SIEGEAMMO",
    "BALLISTAARROWHEAD",
    "TRAPPARTS",
    "TRAPCOMP",
    "DRINK",
    "POWDER_MISC",
    "CHEESE",
    "FOOD",
    "LIQUID_MISC",
    "COIN",
    "GLOB",
    "ROCK",
    "PIPE_SECTION",
    "HATCH_COVER",
    "GRATE",
    "QUERN",
    "MILLSTONE",
    "SPLINT",
    "CRUTCH",
    "TRACTION_BENCH",
    "ORTHOPEDIC_CAST",
    "TOOL",
    "SLAB",
    "EGG",
    "BOOK",
    "SHEET",
    "BRANCH",
    "BOLT_THROWER_PARTS",

];

data["flags"] = [
    "improvable",
    "butcherable",
    "millable",
    "allow_buryable",
    "unrotten",
    "undisturbed",
    "collected",
    "sharpenable",
    "murdered",
    "empty",
    "processable",
    "cookable",
    "extract_bearing_plant",
    "extract_bearing_fish",
    "extract_bearing_vermin",
    "processable_to_vial",
    "processable_to_barrel",
    "solid",
    "tameable_vermin",
    "nearby",
    "sand_bearing",
    "glass",
    "milk",
    "milkable",
    "finished_goods",
    "ammo",
    "furniture",
    "not_bin",
    "lye_bearing",
    "dye",
    "dyeable",
    "dyed",
    "sewn_imageless",
    "glass_making",
    "screw",
    "building_material",
    "fire_safe",
    "magma_safe",
    "deep_material",
    "melt_designated",
    "non_economic",
    "allow_melt_dump",
    "allow_artifact",
    "plant",
    "silk",
    "leather",
    "bone",
    "shell",
    "totemable",
    "horn",
    "pearl",
    "plaster_containing",
    "soap",
    "body_part",
    "ivory_tooth",
    "lye_milk_free",
    "blunt",
    "unengraved",
    "hair_wool",
    "yarn",
    "unimproved",
    "any_raw_material",
    "non_absorbent",
    "non_pressed",
    "allow_liquid_powder",
    "any_craft",
    "hard",
    "food_storage",
    "metal",
    "sand",
    "can_use_location_reserved",
    "written_on",
    "edged",
    "on_ground",
    "divine",
    "crafted_artifact",
    "wood",
    "stone",
    "non_artifact",
    "woven",
    "gem",
    "empty_or_water",
    "grown_not_crafted",
];